# Site config ----------------------------------
title: Docs theme
description: Docs theme description
baseurl: "/lindebrothers/classroom-theme"
repository: lindebrothers/classroom-theme
repository_name: classroom-theme

# template configurations -------------------
main_docs_repo_url: /
main_docs_name: lindebrosthers classroom theme
host_url: https://www.github.com
footer_sign: by developers @ Blocket
logo_url: /_assets/images/theme/logo-inverted.svg
host_org_name: https://pages.github.schibsted.io/blocket
# Classrooms and Pages config ---------------------------------
collections:
  classroom:
    output: true
    tags:
      - docs
    title: Sample classroom in an external repo

defaults:
  -
    scope:
      path: ""
      type: classroom
    values:
      authors:
        - jlindebro
      permalink: /:collection/:name


# Build config ----------------------------------
#markdown: kramdown
#kramdown:
#  input: GFM
#  syntax_highlighter: rouge
#  syntax_highlighter_opts:
#    css_class: 'hoppsan'
markdown: redcarpet
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables", "with_toc_data"]

include: ['_posts', 'assets', '_pages', '_series']
exclude: ['.sass_cache', 'README.md', 'docker-compose.yml', 'dev', 'Dockerfile']
sass:
  sass_dir: 'assets/_sass'
plugins:
  - jekyll-github-metadata

whitelist:
  - jekyll-redirect-from
collections_dir: classrooms

# Pages config ---------------------------------



